# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTau2 <- function(ORIG_ID, x, y, onset, r, r_low, index) {
    .Call(`_taustatisticspeedup_getTau2`, ORIG_ID, x, y, onset, r, r_low, index)
}

getTau3 <- function(ORIG_ID, x, y, onset, r, r_low, index) {
    .Call(`_taustatisticspeedup_getTau3`, ORIG_ID, x, y, onset, r, r_low, index)
}

getTau23 <- function(ORIG_ID, x, y, onset, r, r_low, index) {
    .Call(`_taustatisticspeedup_getTau23`, ORIG_ID, x, y, onset, r, r_low, index)
}

