# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTau <- function(ORIG_ID, x, y, onset, r, r_low, index) {
    .Call(`_anRpackage_getTau`, ORIG_ID, x, y, onset, r, r_low, index)
}

rcpp_hello_world <- function() {
    .Call(`_anRpackage_rcpp_hello_world`)
}

